apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "helm.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "helm.fullname" . }}
    spec:
      containers:
        - name: node-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: {{ include "helm.fullname" . }}-mongo-secret
                  key: MONGODB_URI
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "helm.fullname" . }}-config
                  key: PORT
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "helm.fullname" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}

