apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm.fullname" . }}-mongo-secret
type: Opaque
stringData:
  MONGODB_URI: "mongodb://{{ .Values.mongo.username }}:{{ .Values.mongo.password }}@{{ include "helm.fullname" . }}-mongo:{{ .Values.mongo.port }}/?authSource=admin"

