replicaCount: 4

image:
  repository: prathammore0025/node-app
  tag: v16
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 3000
  nodePort: 32000

mongo:
  image: mongo
  username: prathm
  password: 12345678p
  port: 27017

config:
  port: 3000

